# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180614_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='books',
            new_name='grades',
        ),
    ]
